### ISSUE TITLE
Java dependency upgrade to version 0.6.0

### ISSUE THREAD

**Issue by mariorodriguespt** [ICIJ/node-tika#10]
With node v4.1.0 this package crashed because of node-java.
Check: https://github.com/joeferner/node-java/issues/250

**Comment by mariorodriguespt** [comment]
Thank you ;)

**Comment by mattcg** [comment]
Thanks for filing the issue!

**Comment by rossj** [comment]
FYI this isn't published on NPM yet. Could you bump the version and publish when you get a chance? Thanks!

**Comment by mattcg** [comment]
Bumped and published! Thank you for pointing that out @rossj
