### ISSUE TITLE
Small issue in documentation

### ISSUE THREAD

**Issue by tomaskulich** [ICIJ/node-tika#8]
According to documentation:

    tika.text('http://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/eng.pdf', 
        function(err, text, meta) {
            // ...
        });

should work. However, later in the documentation is stated that you need to call `tika.extract` to get also the metadata; `tika.text` feeds callback only with extracted text. (confirmed by an experiment :) )

**Comment by mattcg** [comment]
Thank you! :space_invader:
